export default {
  'sh': 'bash',
  'c': 'cpp',
  'c++': 'cpp',
  'cs': 'cs',
  'css': 'css',
  'delphi': 'delphi',
  'diff': 'diff',
  'dos': 'dos',
  'excel': 'excel',
  'go': 'go',
  'java': 'java',
  'javascript': 'javascript',
  'json': 'json',
  'kotlin': 'kotlin',
  'lua': 'lua',
  'markdown': 'markdown',
  'php': 'php',
  'powershell': 'powershell',
  'python': 'python',
  'ruby': 'ruby',
  'shell': 'shell',
  'sql': 'sql',
  'vbscript': 'vbscript',
  'xml': 'xml',
  'html': 'xml',
  'yaml': 'yaml',
};
